### ISSUE TITLE
NoSuchMethodError thrown when authn_method unset/zero-length with CAS 3.5.2.1/CAS-MFA 1.0.0-M6

### ISSUE THREAD

**Issue by xraj** [Unicon/cas-mfa#115]
With the mfa/duo plugins installed, any login request for a service entry that does not set authn_method will cause the request to blow up with an exception.

```
java.lang.NoSuchMethodError: org.springframework.util.StringUtils.isEmpty(Ljava/lang/Object;)Z
```

If auth_method is set to a valid value, the login request will work as expected. It is my understanding from the wiki entry for M6 that authn_method may be left unset and should result in an unmodified CAS flow.

Maven overlay and detailed stack traces located in bitbucket snippet.
https://bitbucket.org/snippets/csusb/gM6ak

**Comment by mmoayyed** [comment]
M6 is over a year old. Lots has happened since then. Please see if you can duplicate the error with the latest version available.

**Comment by xraj** [comment]
Last time I tried one of the RC releases, I couldn't even get the context to boot up. M6 is last release with wiki documentation. Is the setup for the RC the same?

**Comment by mmoayyed** [comment]
Yes. It should be the same. You could also  use:
https://github.com/Unicon/cas-mfa/tree/master/cas-mfa-overlay

Your overlay likely has conflicting JARs. It's something we have fixed in the latest RC

**Comment by xraj** [comment]
Tomcat7 + CAS 3.6 + CAS-MFA RC6 get a similar backtrace only the request blows up so badly that the error page doesn't even render. This happens as soon as I put a ?service= parameter on the login view. Without a service parameter, the login view renders fine.

```
2015-07-29 22:31:12,023 ERROR [org.springframework.web.servlet.tags.ThemeTag] - <null>
java.lang.NullPointerException
	at net.unicon.cas.mfa.web.support.RegisteredServiceAttributeMultiFactorAuthenticationArgumentExtractor.checkMfaRoles(RegisteredServiceAttributeMultiFactorAuthenticationArgumentExtractor.java:142)
	at net.unicon.cas.mfa.web.support.RegisteredServiceAttributeMultiFactorAuthenticationArgumentExtractor.getAuthenticationMethod(RegisteredServiceAttributeMultiFactorAuthenticationArgumentExtractor.java:74)
	at net.unicon.cas.mfa.web.support.AbstractMultiFactorAuthenticationArgumentExtractor.extractService(AbstractMultiFactorAuthenticationArgumentExtractor.java:71)
	at net.unicon.cas.mfa.web.support.MultiFactorAuthenticationRequestsCollectingArgumentExtractor.extractService(MultiFactorAuthenticationRequestsCollectingArgumentExtractor.java:64)
	at org.jasig.cas.web.support.WebUtils.getService_aroundBody4(WebUtils.java:68)
	at org.jasig.cas.web.support.WebUtils.getService_aroundBody5$advice(WebUtils.java:57)
	at org.jasig.cas.web.support.WebUtils.getService(WebUtils.java:1)
	at org.jasig.cas.services.web.ServiceThemeResolver.resolveThemeName_aroundBody0(ServiceThemeResolver.java:59)
	at org.jasig.cas.services.web.ServiceThemeResolver.resolveThemeName_aroundBody1$advice(ServiceThemeResolver.java:57)
	at org.jasig.cas.services.web.ServiceThemeResolver.resolveThemeName(ServiceThemeResolver.java:1)
	at org.springframework.web.servlet.support.RequestContextUtils.getTheme(RequestContextUtils.java:151)
	at org.springframework.web.servlet.support.RequestContext.getTheme(RequestContext.java:318)
	at org.springframework.web.servlet.tags.ThemeTag.getMessageSource(ThemeTag.java:50)
	at org.springframework.web.servlet.tags.MessageTag.resolveMessage(MessageTag.java:193)
	at org.springframework.web.servlet.tags.MessageTag.doStartTagInternal(MessageTag.java:165)
	at org.springframework.web.servlet.tags.RequestContextAwareTag.doStartTag(RequestContextAwareTag.java:79)
	at org.apache.jsp.WEB_002dINF.view.jsp.errors_jsp._jspx_meth_spring_005ftheme_005f0(errors_jsp.java:193)
	at org.apache.jsp.WEB_002dINF.view.jsp.errors_jsp._jspService(errors_jsp.java:92)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:488)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:476)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:345)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:437)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:208)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mmoayyed** [comment]
I ran through the scenario; so far cannot duplicate. 

my service registry:

```json
{
    "services":[
        {
            "id":1,
            "serviceId":"^(https?|imaps?)://.*",
            "name":"HTTP/HTTPS service",
            "description":"Test HTTP/HTTPS services",
            "allowedToProxy": true
        }		
    ]
}
```

my attributes:

```json
{
    "casuser":{
		"firstName":["Misagh"],
		"lastName":["Moayyed"],
		"cn": ["Bombadil, Tom"]
	}
}
```

Duo installed and logged into a sample webapp just fine without DUO prompts.

**Comment by mmoayyed** [comment]
Your overlay is also not configured to externalize the cas.properties file. I had to add a sample. Then, I was able to duplicate the stacktrace you had. Ended up fixing the issue. Point your overlay to 1.0.0-RC7-SNAPSHOT and try again please.

**Comment by xraj** [comment]
By externalize cas.properites you mean set the location to /etc/cas/cas.properties in src/main/webapp/WEB-INF/spring-configuration/propertyFileConfigurer.xml? I'm pretty sure that should have been included in the snippet I linked.

**Comment by mmoayyed** [comment]
ah, ok then. I may have skipped over that part, seeing I just downloaded the pom. Good deal then. As soon as RC7-SNAPSHOT becomes available in central which should be in 10-15mins, feel free to try again.

**Comment by mmoayyed** [comment]
Looks like it's ready now:
https://travis-ci.org/Unicon/cas-mfa/builds/73323968

**Comment by xraj** [comment]
Hot diggity. No more stacktrace.

**Comment by xraj** [comment]
I'll test this out more thoroughly when I get in the office tomorrow. The immediate issue seems to be resolved though. I think we can close the issue.

Many thanks.

**Comment by mmoayyed** [comment]
Pleasure
